Bentley fixes 2017
artefactual-labs/appraisal-tab pull request #152
Opened 2017-02-09 17:05 UTC by jraddaoui

Includes fixes for:

https://projects.artefactual.com/issues/10807
https://projects.artefactual.com/issues/10806

See the commit messages for more details.

2017-02-14 23:10 UTC, sevein commented
@jraddaoui sorry, I think this needs to be refactored into four pull requests! Thank you!

2017-02-14 23:11 UTC, sevein requested changes
@jraddaoui sorry, I think this needs to be refactored into four pull requests! Thank you!

2017-02-15 16:31 UTC, jraddaoui commented
Hi @sevein, the first three commits are closely related and splitting them in diferent PRs creates a lot of conflicts in the process and it will create more while merging. I'll leave those three in here with a better message that we can merge after with --squash, and I'll move the last one to another PR.

2017-02-15 20:00 UTC, sevein approved these changes
It works and I think it's ready to be merged.

I have a couple of nitpicks but feel free to ignore them.

The following is a screenshot of the file list pane when it's empty:

![001](https://cloud.githubusercontent.com/assets/606459/22992398/743c2d22-f374-11e6-852b-0e93fa20230f.png)

I would move the empty message to the body of the pane, e.g.:

![002](https://cloud.githubusercontent.com/assets/606459/22992405/77ab7076-f374-11e6-8901-fdd78470b491.png)

My next comment is about the path column. I think the solution is okay but I personally prefer when [the text that overflows is hidden using ellipsis](http://jsfiddle.net/maruxa1j/) with `text-overflow`. The user could still see the full text if the cursor is positioned over the text (with the `alt` attr?) or using a Boostrap popover. Something like:

![003](https://cloud.githubusercontent.com/assets/606459/22992965/25945be8-f376-11e6-8b4c-623978194dbb.png)

In my screenshot I've removed the padding of the body pane so the table can use the extra space, which also contributes to the path column issue.

2017-02-16 13:53 UTC, jraddaoui commented
Thanks @sevein!

About the message, I like it more in there so it's in the same place as the counts when the table is populated, it's also the same in the backlog panel.

About the other nitpicks, I really like them, but I've spent all the time allocated to this changes. Maybe we could make them in the remaining ticket if things go well.

2017-02-16 14:07 UTC, jraddaoui commented
Merged in https://github.com/artefactual-labs/appraisal-tab/commit/eea84c7cc4ae4a665c68344f0b08b91902a877d9

2017-02-16 14:07 UTC, closed without merging